---
- include_vars: ../../telegraf/defaults/main.yml

- name: configure grafana repo
  copy: src=grafana.repo dest=/etc/yum.repos.d/grafana.repo owner=root group=root

- name: install grafana
  yum: name=grafana-{{ grafana.version }} state=present

- name: configure grafana
  template: src=grafana.ini.j2 dest={{ grafana.conf_dir }}/grafana.ini
  notify:
    - restart grafana

- meta: flush_handlers

- name: start grafana-server
  service: name=grafana-server enabled=yes state=started

- name: install python-httplib2.noarch
  yum: name=python-httplib2.noarch state=present

- wait_for: port={{ grafana.port }} delay=10 timeout=20

- name: setup upswing datasource in grafana
  uri:
    url: http://{{ grafana.host }}:{{ grafana.port }}/api/datasources
    method: POST
    body: "{{ lookup('template','datasource.json') }}"
    user: "{{ grafana.admin }}"
    password: "{{ grafana.admin_password }}"
    force_basic_auth: yes
    body_format: json
    HEADER_Content-Type: "application/json"
    status_code: 200,500

- name: set up upswing dashboard
  uri:
    url: http://{{ grafana.host }}:{{ grafana.port }}/api/dashboards/db
    method: POST
    body: "{{ lookup('template','upswing_nodes.json') }}"
    user: "{{ grafana.admin }}"
    password: "{{ grafana.admin_password }}"
    force_basic_auth: yes
    body_format: json
    HEADER_Content-Type: "application/json"
    status_code: 200,412
