---
- name: Create new Droplet
  digital_ocean:
    state: present
    command: droplet
    name: "{{ node.name }}"
    private_networking: yes
    size_id: 512mb
    image_id: centos-7-0-x64
    region_id: sgp1
    ssh_key_ids: "{{ ssh_key_id }}"
    unique_name: yes
  register: do

- name: Add new host to a group
  add_host:
    name: "{{ do.droplet.ip_address }}"
    groups: "{{ node.groups }}"
  when: do.droplet is defined
  changed_when:  false

- name: Wait for the port to become available
  local_action: "wait_for port=22 host={{ do.droplet.ip_address }}"
  become: no
