---
- name: setup repo
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root

- name: install docker
  yum: name=docker-engine state=present

- name: configure docker unit file
  template: src=docker.service dest=/etc/systemd/system/docker.service
  notify:
    - reload systemd
    - restart docker

- meta: flush_handlers

- name: start docker deamon
  service: name=docker enabled=yes state=started

- name: test if service is running
  command: docker images
  changed_when: false
