---

- hosts: all
  roles:
    - common

- hosts: etcd_masters
  roles:
    - etcd

- hosts: all
  roles:
    - docker

- hosts: swarm_master
  roles:
    - swarm_master

- hosts: all
  roles:
    - swarm_agent
